### ISSUE TITLE
Error: Verifying response failed. After selecting and saving bank account.

### ISSUE THREAD

**Issue by TrueFawkes** [patrickkivits/bunq-for-woocommerce#20] opened 2024-02-26 15:31 UTC
When I authenticate and get redirected back to wordpress, I can select my "Bank account".
When pressing save afterwards I only get the message "Error: Verifying response failed.".

The same error also shows on the checkout page.
![image](https://github.com/patrickkivits/bunq-for-woocommerce/assets/24944520/c4dc9243-8907-47ed-a238-7a3fdb33627b)
![Capture](https://github.com/patrickkivits/bunq-for-woocommerce/assets/24944520/74c77b2e-7a56-48cb-8e48-3caee7f4965e)

Edit; I meet all requirements.
HTTPS/SSL certificate (for callbacks/payment processing to work)
PHP version: == 8.1.27
PHP extensions: openssl, curl, json, mbstring (all enabled)
Wordpress version: == 6.4.3
WooCommerce version: == 8.6.1

Nederlands kan ook evt.

**Comment by gweisama** [comment] 2024-02-26 20:15
Thank you so much for raising this issue, I got the same thing happening to me a couple hours later. Exact same versions of wordpress/woo/PHP etc.

Have you found a solution?

**Comment by TrueFawkes** [comment] 2024-02-26 20:21
@gweisama 
Comforting to know I-am not the only one.
Sadly no solution yet. I can see the demo site still works.

**Comment by gweisama** [comment] 2024-02-26 20:25
Damn... what OAuth redirect url did you use? Did you just change the example.com to your own domain?
We need to see if we can fix it ourselves as the developer hasn't really been active lately. Demo site still works yes.

Ik zie trouwens wel dat bij 'API KEYS' onder bunq er staat dat de API key nog 'niet toegewezen' is, maar ik krijg geen API error. Wat zou dit kunnen zijn?

**Comment by TrueFawkes** [comment] 2024-02-26 20:28
@gweisama 
The OAuth redirect has successfully been configured (also got redirected succesfully when setting up the OAuth.).
Please create a new issue for any other problems.

**Comment by gweisama** [comment] 2024-02-26 20:29
TrueFawkes, I got you. No other problems anymore.

When you click on OAuth Authorization Request (here)
<img width="216" alt="Screenshot 2024-02-26 at 21 29 12" src="https://github.com/patrickkivits/bunq-for-woocommerce/assets/161378193/1a9a970c-74be-41ed-967b-3dba3820e337">

Click on the bank account, and DO NOT CLICK SAVE after. It already saved.

**Comment by gweisama** [comment] 2024-02-26 20:31
clicking the save button after everything works correctly sets the error in motion.
so, after the auth. req. do nothing and just test it out on your website. it works for me now, so it should work for you too.

**Comment by TrueFawkes** [comment] 2024-02-26 20:35
@gweisama 
Amazing, I just tried.
Not clicking the save button is indeed the work-around.
That's however a critical bug @patrickkivits 

Thank you for sharing your findings!
I'll check if it also works on the checkout page.

**Comment by patrickkivits** [comment] 2024-02-26 21:12
Thank you @TrueFawkes and @gweisama for your comments here. This will help me track down and reproduce this bug. I will look into resolving this!

**Comment by patrickkivits** [comment] 2024-03-06 22:11
I created a new (pre)release that fixes this: https://github.com/patrickkivits/bunq-for-woocommerce/releases/tag/v1.2.11

Please let me know if the issue is still not resolved after updating to v1.2.11.

**Closed by patrickkivits** 2024-03-06 22:11 UTC
Labels: bug
